name: Build and Release Resource Pack

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip Resource Pack
        run: |
          zip -r resource-pack.zip . -x ".github/*" -x "README.md"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Asset to Release
        uses: softprops/action-gh-release@v1
        with:
          files: resource-pack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
